apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
stringData:
  # 파트4 담당자와 맞춘 MySQL 계정 정보
  # 실제 배포 시 아래 값을 팀 내부 공유 값으로 변경
  MYSQL_USER: "trainuser"
  MYSQL_PASSWORD: "trainpass123"
